exclude:
- /docs/.*
component_depth: 3
languages:
- name: python
  production:
    include:
      - src/software_patterns/*.py
    exclude:
      - docs/conf.py
  test:
    include:
      - tests/*.py
